name: Node.js Package

on:
  push:
    branches:
      - npm

  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: npm
          
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: https://registry.npmjs.org/
        
      - name: Publish Package
        run: |
          git config --global user.email "publish-npm@yfun.top"
          git config --global user.name "Publish NPM Bot"
          npm version prepatch
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
